# 导航栏以及图标 图标网址：https://feathericons.com/
menu:
  首页: 
    - /
    - home
  归档: 
    - /archives
    - archive
  关于:
    - /about
    - alert-circle
  留言:
    - /board
    - edit-3

# 自定义颜色
color:
  bg: "#1653A6"
  bg_dark: "#13478d"
  bg_light: "#195fbf"
  normal_text: "#F0F0F0"
  highlight: "#E3C36F"

# Sidebar
sidebar: left
widgets:
- info

# 网站个性化
icon_img: ../img/icon.png #标签页图标
site_author: 向来痴
signature: 业精于勤，荒于嬉。  #个性签名
site_name: 无名BLOG
avator_img: ../img/avator.jpg #头像

# Valine 评论系统
valine:
  open: true # true | false 是否打开，默认false
  appid: HBismw2vU6hg56PslAF2APW1-gzGzoHsz  #Leancloud应用的AppID
  appkey: k41e2BJYdNbojyHuMnKT5LBK  #Leancloud应用的AppKey
  verify: false #验证码
  notify: true #评论回复提醒
  avatar: robohash #评论列表头像样式：''/mm/identicon/monsterid/wavatar/retro/hide
  #头像类型可见： https://valine.js.org/avatar.html
  placeholder: 留下你来过的痕迹~ #评论框占位符

# 不蒜子统计
busuanzi:
  open: true # true | false 是否打开，默认false

